### ISSUE TITLE
is this project is still in update now?

### ISSUE THREAD

**Issue by naixiaoxian** [paul-thebaud/phpunit-generator#4]
exceuse me .i wanna know whether the project is work .because i want to update it and use in my project .of course . if it  there is something improved i will push or make a mr

**Comment by paul-thebaud** [comment]
Hi @naixiaoxian,
The phpunit-generator package is deprecated in favor of the new version, phpunitgen-core and phpunitgen-console. You should migrate to the new version, because it is actively maintained.
Are you already using phpunit-generator? What are/will you do with it?
If I can help you to setup/migrate to the new version, feel free to ask.
You will find useful information on the new version on the [web application](https://phpunitgen.io).

**Comment by paul-thebaud** [comment]
Hi @naixiaoxian,
I'm closing the issue as you didn't answer. Feel free to re-open if you need.
